// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "./verifier.sol"; // Groth16 verifier generated by circom

/**
 * @title PrivacyVerifier
 * @dev 零知识证明隐私保护验证合约
 * 使用zk-SNARKs实现隐私保护的侵权验证，仅返回是否侵权，不泄露原文内容
 */
contract PrivacyVerifier {
    // Groth16验证器实例
    Verifier public immutable verifier;
    
    // 学术成果版权合约地址
    address public academicCopyrightContract;
    
    // 隐私验证记录
    struct PrivacyVerification {
        address verifier_addr;
        uint256 timestamp;
        bool isInfringement;
        bytes32 nullifierHash; // 防止重复验证的nullifier
    }
    
    // 存储映射
    mapping(bytes32 => PrivacyVerification) public verifications;
    mapping(bytes32 => bool) public usedNullifiers;
    
    // 事件
    event PrivacyVerificationCompleted(
        bytes32 indexed nullifierHash,
        address indexed verifier_addr,
        bool isInfringement,
        uint256 timestamp
    );
    
    constructor(address _verifier, address _academicCopyrightContract) {
        verifier = Verifier(_verifier);
        academicCopyrightContract = _academicCopyrightContract;
    }
    
    /**
     * @dev 零知识证明隐私验证
     * @param _pA zk-SNARK证明的A部分
     * @param _pB zk-SNARK证明的B部分
     * @param _pC zk-SNARK证明的C部分
     * @param _h zk-SNARK证明的H部分
     * @param _k zk-SNARK证明的K部分
     * @param _inputs 公开输入数组
     * @return isValid 验证是否成功
     * @return isInfringement 是否构成侵权
     */
    function verifyPrivacy(
        uint[2] memory _pA,
        uint[2][2] memory _pB,
        uint[2] memory _pC,
        uint[2] memory _h,
        uint[2] memory _k,
        uint[] memory _inputs
    ) public returns (bool isValid, bool isInfringement) {
        // 检查输入参数
        require(_inputs.length >= 2, "Invalid inputs length");
        
        bytes32 nullifierHash = bytes32(_inputs[0]);
        bytes32 commitmentHash = bytes32(_inputs[1]);
        
        // 检查nullifier是否已使用（防止重复验证）
        require(!usedNullifiers[nullifierHash], "Nullifier already used");
        
        // 验证zk-SNARK证明
        isValid = verifier.verifyTx(_pA, _pB, _pC, _h, _k, _inputs);
        require(isValid, "Invalid zk-SNARK proof");
        
        // 标记nullifier为已使用
        usedNullifiers[nullifierHash] = true;
        
        // 从证明中提取侵权结果（这里简化处理）
        // 实际应用中，侵权结果应该从zk-SNARK电路的公开输出中获取
        isInfringement = (_inputs.length > 2) ? (_inputs[2] == 1) : false;
        
        // 记录验证结果
        verifications[nullifierHash] = PrivacyVerification({
            verifier_addr: msg.sender,
            timestamp: block.timestamp,
            isInfringement: isInfringement,
            nullifierHash: nullifierHash
        });
        
        emit PrivacyVerificationCompleted(
            nullifierHash,
            msg.sender,
            isInfringement,
            block.timestamp
        );
        
        return (isValid, isInfringement);
    }
    
    /**
     * @dev 获取隐私验证记录
     * @param nullifierHash nullifier哈希
     * @return 验证记录
     */
    function getVerificationRecord(bytes32 nullifierHash) 
        public 
        view 
        returns (PrivacyVerification memory) 
    {
        return verifications[nullifierHash];
    }
    
    /**
     * @dev 检查nullifier是否已使用
     * @param nullifierHash nullifier哈希
     * @return 是否已使用
     */
    function isNullifierUsed(bytes32 nullifierHash) public view returns (bool) {
        return usedNullifiers[nullifierHash];
    }
}
